"""initial schema

Revision ID: e0695f4f8237
Revises: 
Create Date: 2026-02-23 18:09:16.157103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0695f4f8237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('native_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('learning_goals', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('preferred_difficulty', sa.String(length=10), nullable=False),
    sa.Column('session_style', sa.String(length=12), nullable=False),
    sa.Column('topics_to_avoid', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('weak_areas', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('strong_areas', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('recent_scores', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('vocabulary_count', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('streak_updated_at', sa.Date(), nullable=True),
    sa.Column('last_activity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('notifications_paused', sa.Boolean(), nullable=False),
    sa.Column('max_notifications_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('notifications_sent_today', sa.SmallInteger(), nullable=False),
    sa.Column('notifications_count_reset_date', sa.Date(), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_notification_text', sa.Text(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IN ('A1','A2','B1','B2','C1','C2')", name='ck_users_level'),
    sa.CheckConstraint("preferred_difficulty IN ('easy','normal','hard')", name='ck_users_difficulty'),
    sa.CheckConstraint("session_style IN ('casual','structured','intensive')", name='ck_users_style'),
    sa.CheckConstraint("tier IN ('free','premium')", name='ck_users_tier'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index('idx_users_active_last_session', 'users', ['last_session_at'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_is_admin', 'users', ['telegram_id'], unique=False, postgresql_where='is_admin = TRUE')
    op.create_index('idx_users_notif_reset', 'users', ['notifications_count_reset_date'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=False),
    sa.Column('pause_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_trigger_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.SmallInteger(), nullable=False),
    sa.Column('notification_tier', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_by IN ('system','user','onboarding')", name='ck_schedules_created_by'),
    sa.CheckConstraint("notification_tier IN ('template','llm','hybrid')", name='ck_schedules_tier'),
    sa.CheckConstraint("schedule_type IN ('daily_review','quiz','progress_report','practice_reminder','custom')", name='ck_schedules_type'),
    sa.CheckConstraint("status IN ('active','paused','expired')", name='ck_schedules_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedules_due', 'schedules', ['next_trigger_at'], unique=False, postgresql_where="status = 'active'")
    op.create_index('idx_schedules_user', 'schedules', ['user_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('num_turns', sa.SmallInteger(), nullable=False),
    sa.Column('tool_calls_count', sa.SmallInteger(), nullable=False),
    sa.Column('tool_calls_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('pipeline_status', sa.String(length=20), nullable=False),
    sa.Column('pipeline_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("pipeline_status IN ('pending','running','completed','failed')", name='ck_sessions_pipeline'),
    sa.CheckConstraint("session_type IN ('interactive','onboarding','proactive_review','proactive_quiz','proactive_summary','proactive_nudge','assessment')", name='ck_sessions_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_pipeline', 'sessions', ['pipeline_status', 'started_at'], unique=False, postgresql_where="pipeline_status IN ('pending', 'failed')")
    op.create_index('idx_sessions_user_recent', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('fsrs_state', sa.SmallInteger(), nullable=False),
    sa.Column('fsrs_stability', sa.Double(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Double(), nullable=True),
    sa.Column('fsrs_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fsrs_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_rating', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vocabulary_due', 'vocabulary', ['user_id', 'fsrs_due'], unique=False)
    op.create_index('idx_vocabulary_user_topic', 'vocabulary', ['user_id', 'topic'], unique=False)
    op.create_index('uq_user_word_ci', 'vocabulary', ['user_id', sa.literal_column('lower(word)')], unique=True)
    op.create_table('exercise_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('max_score', sa.SmallInteger(), nullable=False),
    sa.Column('words_involved', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 10', name='ck_exercise_score'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exercise_results_session', 'exercise_results', ['session_id'], unique=False)
    op.create_index('idx_exercise_results_user_time', 'exercise_results', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_exercise_results_user_topic', 'exercise_results', ['user_id', 'topic', 'score'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('sent','skipped_quiet','skipped_paused','skipped_preference','skipped_limit','skipped_dedup','failed')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_schedule', 'notifications', ['schedule_id'], unique=False)
    op.create_index('idx_notifications_session', 'notifications', ['session_id'], unique=False)
    op.create_index('idx_notifications_user_time', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('vocabulary_review_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vocabulary_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 4', name='ck_review_rating'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_log_user', 'vocabulary_review_log', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_review_log_vocab', 'vocabulary_review_log', ['vocabulary_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_log_vocab', table_name='vocabulary_review_log')
    op.drop_index('idx_review_log_user', table_name='vocabulary_review_log')
    op.drop_table('vocabulary_review_log')
    op.drop_index('idx_notifications_user_time', table_name='notifications')
    op.drop_index('idx_notifications_session', table_name='notifications')
    op.drop_index('idx_notifications_schedule', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_exercise_results_user_topic', table_name='exercise_results')
    op.drop_index('idx_exercise_results_user_time', table_name='exercise_results')
    op.drop_index('idx_exercise_results_session', table_name='exercise_results')
    op.drop_table('exercise_results')
    op.drop_index('uq_user_word_ci', table_name='vocabulary')
    op.drop_index('idx_vocabulary_user_topic', table_name='vocabulary')
    op.drop_index('idx_vocabulary_due', table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index('idx_sessions_user_recent', table_name='sessions')
    op.drop_index('idx_sessions_pipeline', table_name='sessions', postgresql_where="pipeline_status IN ('pending', 'failed')")
    op.drop_table('sessions')
    op.drop_index('idx_schedules_user', table_name='schedules')
    op.drop_index('idx_schedules_due', table_name='schedules', postgresql_where="status = 'active'")
    op.drop_table('schedules')
    op.drop_index('idx_users_notif_reset', table_name='users', postgresql_where='is_active = TRUE')
    op.drop_index('idx_users_is_admin', table_name='users', postgresql_where='is_admin = TRUE')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_active_last_session', table_name='users', postgresql_where='is_active = TRUE')
    op.drop_table('users')
    # ### end Alembic commands ###
